<?xml version="1.0" encoding="utf-8"?>
<feature>
	<version>1</version>
	<uuid>fe85452a-0452-4374-8224-f3b31e4834cb</uuid>
	<name>Surface Plot 1</name>
	<type>1</type>
	<res_file_key>0e8556a4-1966-4955-ba9a-221cd424d847</res_file_key>
	<cs_name/>
	<cs_uuid/>
	<x_form>
		<global>true</global>
		<origin>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</origin>
		<translate>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
		</translate>
	</x_form>
	<display_bl>false</display_bl>
	<interpolate>true</interpolate>
	<use_cad_geom>true</use_cad_geom>
	<moving_reference>true</moving_reference>
	<moving_display>true</moving_display>
	<full_task>false</full_task>
	<use_in_BRP>false</use_in_BRP>
	<transparency>0</transparency>
	<box>
		<item>0.50789906454773559</item>
		<item>0.86092517893782805</item>
		<item>-0.0019205563148836369</item>
		<item>1.9706794436851154</item>
		<item>1.475124288758642</item>
		<item>2.9119269961679071</item>
	</box>
	<crop_region_anchors>
		<item>false</item>
		<item>false</item>
		<item>false</item>
		<item>false</item>
		<item>false</item>
		<item>false</item>
	</crop_region_anchors>
	<section_plane/>
	<use_all_faces>false</use_all_faces>
	<geom_ref>
		<item>
			<uuid>92918bd5-8408-4d52-b29b-682ebfbfbc88</uuid>
			<name>Face&lt;1&gt;@zphr-aerod-Control Surface -v2_1&lt;1&gt;</name>
			<type>5</type>
			<id1>0</id1>
			<id2>0</id2>
			<update_stamp>0</update_stamp>
			<group>-1</group>
			<geom_stamp_uuid>50a94030-af17-45cb-8c6a-3fee13f26923</geom_stamp_uuid>
			<origin>
				<item>0.68441212174278188</item>
				<item>0.9767857006891425</item>
				<item>2.1935256424632743</item>
			</origin>
			<normal>
				<item>-0.069098240146133458</item>
				<item>-0.99756405025982431</item>
				<item>-0.0095602739459779307</item>
			</normal>
			<vector>
				<item>-0.00033070183902041296</item>
				<item>-0.0095602739459779325</item>
				<item>0.99995424485241913</item>
			</vector>
			<pos>0</pos>
			<flip>1</flip>
			<min>-1.0105375231505289</min>
			<max>0.99538703311113796</max>
			<curve_data>
				<start>0</start>
				<end>0</end>
				<length>0</length>
				<data/>
			</curve_data>
			<path>
				<path_elems/>
			</path>
		</item>
	</geom_ref>
	<domain_filter>
		<enabled>false</enabled>
		<keep>true</keep>
		<type>0</type>
		<domains/>
	</domain_filter>
	<contours>
		<display>true</display>
		<palette>
			<uuid>8990731f-264f-49c2-a158-5e2da04f94f9</uuid>
			<parameter>
				<uuid>88A4B00C-3C32-4822-94C2-4682145D4F95</uuid>
				<name/>
				<unit>0</unit>
				<formula/>
				<formula2/>
				<formula3/>
				<locality>0</locality>
			</parameter>
			<param_min>
				<value>100842.39007741267</value>
				<is_initialized>true</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_min>
			<param_max>
				<value>102730.07982447979</value>
				<is_initialized>true</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_max>
			<cs_uuid/>
			<cs_xform>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</cs_xform>
			<color_palette>5</color_palette>
			<ncolors>9</ncolors>
			<outer_minmax_coloring>0</outer_minmax_coloring>
			<outer_min_color>16711680</outer_min_color>
			<outer_max_color>255</outer_max_color>
			<outer_colors_display>true</outer_colors_display>
			<logarithmic>false</logarithmic>
			<custom_params_maxs/>
			<custom_params_mins/>
			<cs_name/>
			<display_plot_names>true</display_plot_names>
			<display_plot_minmaxes>false</display_plot_minmaxes>
			<display_title>false</display_title>
			<title/>
			<auto_scale_font>false</auto_scale_font>
			<use_default_font>true</use_default_font>
			<font>
				<name/>
				<size>9</size>
				<color>0</color>
				<font_isbold>false</font_isbold>
				<font_isitalic>false</font_isitalic>
			</font>
			<bkgd_color>16777215</bkgd_color>
			<bkgd_transp>1</bkgd_transp>
			<x>0</x>
			<y>0</y>
			<width>20</width>
			<height>200</height>
			<auto_ticks>true</auto_ticks>
			<ticks_number>11</ticks_number>
			<vertical>3</vertical>
			<rot_text>false</rot_text>
			<is_user_pos>false</is_user_pos>
		</palette>
		<color_by_param>true</color_by_param>
		<color>16711680</color>
	</contours>
	<min_callout>
		<display>false</display>
		<coordinates>false</coordinates>
		<appearance>
			<title>true</title>
			<title_source>0</title_source>
			<use_default_font>true</use_default_font>
			<font>
				<name/>
				<size>9</size>
				<color>0</color>
				<font_isbold>false</font_isbold>
				<font_isitalic>false</font_isitalic>
			</font>
			<value_color>16777215</value_color>
			<title_color>16758122</title_color>
			<line_color>0</line_color>
			<auto_line_color>true</auto_line_color>
			<transparency>0</transparency>
			<pinned>false</pinned>
			<show_results>true</show_results>
		</appearance>
		<position_initialized>false</position_initialized>
		<position>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</position>
	</min_callout>
	<max_callout>
		<display>false</display>
		<coordinates>false</coordinates>
		<appearance>
			<title>true</title>
			<title_source>0</title_source>
			<use_default_font>true</use_default_font>
			<font>
				<name/>
				<size>9</size>
				<color>0</color>
				<font_isbold>false</font_isbold>
				<font_isitalic>false</font_isitalic>
			</font>
			<value_color>16777215</value_color>
			<title_color>8026879</title_color>
			<line_color>0</line_color>
			<auto_line_color>true</auto_line_color>
			<transparency>0</transparency>
			<pinned>false</pinned>
			<show_results>true</show_results>
		</appearance>
		<position_initialized>false</position_initialized>
		<position>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</position>
	</max_callout>
	<isolines>
		<display>false</display>
		<palette>
			<uuid>8990731f-264f-49c2-a158-5e2da04f94f9</uuid>
			<parameter>
				<uuid>88A4B00C-3C32-4822-94C2-4682145D4F95</uuid>
				<name/>
				<unit>0</unit>
				<formula/>
				<formula2/>
				<formula3/>
				<locality>0</locality>
			</parameter>
			<param_min>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_min>
			<param_max>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_max>
			<cs_uuid/>
			<cs_xform>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</cs_xform>
			<color_palette>5</color_palette>
			<ncolors>9</ncolors>
			<outer_minmax_coloring>0</outer_minmax_coloring>
			<outer_min_color>16711680</outer_min_color>
			<outer_max_color>255</outer_max_color>
			<outer_colors_display>true</outer_colors_display>
			<logarithmic>false</logarithmic>
			<custom_params_maxs/>
			<custom_params_mins/>
			<cs_name/>
			<display_plot_names>true</display_plot_names>
			<display_plot_minmaxes>false</display_plot_minmaxes>
			<display_title>false</display_title>
			<title/>
			<auto_scale_font>false</auto_scale_font>
			<use_default_font>true</use_default_font>
			<font>
				<name/>
				<size>9</size>
				<color>0</color>
				<font_isbold>false</font_isbold>
				<font_isitalic>false</font_isitalic>
			</font>
			<bkgd_color>16777215</bkgd_color>
			<bkgd_transp>1</bkgd_transp>
			<x>0</x>
			<y>0</y>
			<width>20</width>
			<height>200</height>
			<auto_ticks>true</auto_ticks>
			<ticks_number>11</ticks_number>
			<vertical>3</vertical>
			<rot_text>false</rot_text>
			<is_user_pos>false</is_user_pos>
		</palette>
		<width>1</width>
		<color_by_param>true</color_by_param>
		<color>0</color>
	</isolines>
	<vectors>
		<display>false</display>
		<build_palette>
			<uuid>2c72b181-914f-4475-872d-5160d155032b</uuid>
			<parameter>
				<uuid>8A88FD9A-C36E-4151-864A-F5BC1C916074</uuid>
				<name/>
				<unit>0</unit>
				<formula/>
				<formula2/>
				<formula3/>
				<locality>0</locality>
			</parameter>
			<param_min>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_min>
			<param_max>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_max>
			<cs_uuid/>
			<cs_xform>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</cs_xform>
			<color_palette>5</color_palette>
			<ncolors>10</ncolors>
			<outer_minmax_coloring>0</outer_minmax_coloring>
			<outer_min_color>16711680</outer_min_color>
			<outer_max_color>255</outer_max_color>
			<outer_colors_display>false</outer_colors_display>
			<logarithmic>false</logarithmic>
			<custom_params_maxs/>
			<custom_params_mins/>
			<cs_name/>
			<display_plot_names>true</display_plot_names>
			<display_plot_minmaxes>false</display_plot_minmaxes>
			<display_title>false</display_title>
			<title/>
			<auto_scale_font>false</auto_scale_font>
			<use_default_font>true</use_default_font>
			<font>
				<name/>
				<size>9</size>
				<color>0</color>
				<font_isbold>false</font_isbold>
				<font_isitalic>false</font_isitalic>
			</font>
			<bkgd_color>16777215</bkgd_color>
			<bkgd_transp>1</bkgd_transp>
			<x>0</x>
			<y>0</y>
			<width>20</width>
			<height>200</height>
			<auto_ticks>true</auto_ticks>
			<ticks_number>11</ticks_number>
			<vertical>3</vertical>
			<rot_text>false</rot_text>
			<is_user_pos>false</is_user_pos>
		</build_palette>
		<palette>
			<uuid>8990731f-264f-49c2-a158-5e2da04f94f9</uuid>
			<parameter>
				<uuid>88A4B00C-3C32-4822-94C2-4682145D4F95</uuid>
				<name/>
				<unit>0</unit>
				<formula/>
				<formula2/>
				<formula3/>
				<locality>0</locality>
			</parameter>
			<param_min>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_min>
			<param_max>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_max>
			<cs_uuid/>
			<cs_xform>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</cs_xform>
			<color_palette>5</color_palette>
			<ncolors>9</ncolors>
			<outer_minmax_coloring>0</outer_minmax_coloring>
			<outer_min_color>16711680</outer_min_color>
			<outer_max_color>255</outer_max_color>
			<outer_colors_display>true</outer_colors_display>
			<logarithmic>false</logarithmic>
			<custom_params_maxs/>
			<custom_params_mins/>
			<cs_name/>
			<display_plot_names>true</display_plot_names>
			<display_plot_minmaxes>false</display_plot_minmaxes>
			<display_title>false</display_title>
			<title/>
			<auto_scale_font>false</auto_scale_font>
			<use_default_font>true</use_default_font>
			<font>
				<name/>
				<size>9</size>
				<color>0</color>
				<font_isbold>false</font_isbold>
				<font_isitalic>false</font_isitalic>
			</font>
			<bkgd_color>16777215</bkgd_color>
			<bkgd_transp>1</bkgd_transp>
			<x>0</x>
			<y>0</y>
			<width>20</width>
			<height>200</height>
			<auto_ticks>true</auto_ticks>
			<ticks_number>11</ticks_number>
			<vertical>3</vertical>
			<rot_text>false</rot_text>
			<is_user_pos>false</is_user_pos>
		</palette>
		<color_by_param>false</color_by_param>
		<color>0</color>
		<vectors_projected>true</vectors_projected>
		<arrow_size>0.02</arrow_size>
		<spacing>0.01</spacing>
		<minmax_arrowsize_ratio>0.001</minmax_arrowsize_ratio>
		<logarithmic_arrows>false</logarithmic_arrows>
		<vistype>0</vistype>
		<dynamic>
			<enabled>false</enabled>
			<width>6</width>
			<arrow_size>32</arrow_size>
			<spacing>8</spacing>
		</dynamic>
	</vectors>
	<essslic>
		<display>false</display>
		<build_palette>
			<uuid>c2eb71c5-9a66-48b8-b426-9878fd621a82</uuid>
			<parameter>
				<uuid>8A88FD9A-C36E-4151-864A-F5BC1C916074</uuid>
				<name/>
				<unit>0</unit>
				<formula/>
				<formula2/>
				<formula3/>
				<locality>0</locality>
			</parameter>
			<param_min>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_min>
			<param_max>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_max>
			<cs_uuid/>
			<cs_xform>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</cs_xform>
			<color_palette>5</color_palette>
			<ncolors>10</ncolors>
			<outer_minmax_coloring>0</outer_minmax_coloring>
			<outer_min_color>16711680</outer_min_color>
			<outer_max_color>255</outer_max_color>
			<outer_colors_display>false</outer_colors_display>
			<logarithmic>false</logarithmic>
			<custom_params_maxs/>
			<custom_params_mins/>
			<cs_name/>
			<display_plot_names>true</display_plot_names>
			<display_plot_minmaxes>false</display_plot_minmaxes>
			<display_title>false</display_title>
			<title/>
			<auto_scale_font>false</auto_scale_font>
			<use_default_font>true</use_default_font>
			<font>
				<name/>
				<size>9</size>
				<color>0</color>
				<font_isbold>false</font_isbold>
				<font_isitalic>false</font_isitalic>
			</font>
			<bkgd_color>16777215</bkgd_color>
			<bkgd_transp>1</bkgd_transp>
			<x>0</x>
			<y>0</y>
			<width>20</width>
			<height>200</height>
			<auto_ticks>true</auto_ticks>
			<ticks_number>11</ticks_number>
			<vertical>3</vertical>
			<rot_text>false</rot_text>
			<is_user_pos>false</is_user_pos>
		</build_palette>
		<palette>
			<uuid>8990731f-264f-49c2-a158-5e2da04f94f9</uuid>
			<parameter>
				<uuid>88A4B00C-3C32-4822-94C2-4682145D4F95</uuid>
				<name/>
				<unit>0</unit>
				<formula/>
				<formula2/>
				<formula3/>
				<locality>0</locality>
			</parameter>
			<param_min>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_min>
			<param_max>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_max>
			<cs_uuid/>
			<cs_xform>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</cs_xform>
			<color_palette>5</color_palette>
			<ncolors>9</ncolors>
			<outer_minmax_coloring>0</outer_minmax_coloring>
			<outer_min_color>16711680</outer_min_color>
			<outer_max_color>255</outer_max_color>
			<outer_colors_display>true</outer_colors_display>
			<logarithmic>false</logarithmic>
			<custom_params_maxs/>
			<custom_params_mins/>
			<cs_name/>
			<display_plot_names>true</display_plot_names>
			<display_plot_minmaxes>false</display_plot_minmaxes>
			<display_title>false</display_title>
			<title/>
			<auto_scale_font>false</auto_scale_font>
			<use_default_font>true</use_default_font>
			<font>
				<name/>
				<size>9</size>
				<color>0</color>
				<font_isbold>false</font_isbold>
				<font_isitalic>false</font_isitalic>
			</font>
			<bkgd_color>16777215</bkgd_color>
			<bkgd_transp>1</bkgd_transp>
			<x>0</x>
			<y>0</y>
			<width>20</width>
			<height>200</height>
			<auto_ticks>true</auto_ticks>
			<ticks_number>11</ticks_number>
			<vertical>3</vertical>
			<rot_text>false</rot_text>
			<is_user_pos>false</is_user_pos>
		</palette>
		<color_by_param>false</color_by_param>
		<color>0</color>
		<vistype>0</vistype>
		<esss_vistype>0</esss_vistype>
		<esss_linespacing>12</esss_linespacing>
		<esss_linewidth>2</esss_linewidth>
		<lic_noisegrainsize>1</lic_noisegrainsize>
		<lic_noisedensity>0.5</lic_noisedensity>
		<lic_contrast>0.10000000000000001</lic_contrast>
		<lic_convsize>64</lic_convsize>
	</essslic>
	<mesh>
		<display>false</display>
		<color>0</color>
	</mesh>
	<background>
		<display>false</display>
		<color>16777215</color>
	</background>
	<outlines_display>true</outlines_display>
	<outlines_color>0</outlines_color>
	<DeformedShape>
		<uuid>f5dfb0fd-42f2-435a-8751-032899014203</uuid>
		<creation_date>1756236503</creation_date>
		<enabled>false</enabled>
		<auto_scale>true</auto_scale>
		<scale/>
		<mode>-1</mode>
	</DeformedShape>
	<medias>
		<item>1</item>
	</medias>
	<mesh_type>0</mesh_type>
	<MeshTypePriority>0</MeshTypePriority>
	<use_offset>false</use_offset>
	<MediaPriority>1</MediaPriority>
</feature>
