<?xml version="1.0" encoding="utf-8"?>
<feature>
	<version>1</version>
	<uuid>9c6a9f83-2879-4296-a1df-f1e8897ef958</uuid>
	<name>Mesh 1 Surface</name>
	<type>1</type>
	<res_file_key>234b2f4b-0cf4-4e7b-8398-4d0d38b86d5e</res_file_key>
	<cs_name/>
	<cs_uuid/>
	<x_form>
		<global>true</global>
		<origin>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</origin>
		<translate>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
		</translate>
	</x_form>
	<display_bl>false</display_bl>
	<interpolate>false</interpolate>
	<use_cad_geom>false</use_cad_geom>
	<moving_reference>true</moving_reference>
	<moving_display>true</moving_display>
	<full_task>false</full_task>
	<use_in_BRP>false</use_in_BRP>
	<transparency>0</transparency>
	<box>
		<item>nan</item>
		<item>nan</item>
		<item>nan</item>
		<item>nan</item>
		<item>nan</item>
		<item>nan</item>
	</box>
	<crop_region_anchors>
		<item>false</item>
		<item>false</item>
		<item>false</item>
		<item>false</item>
		<item>false</item>
		<item>false</item>
	</crop_region_anchors>
	<section_plane/>
	<use_all_faces>false</use_all_faces>
	<geom_ref>
		<item>
			<uuid>0892d366-71fc-4dc2-8d30-b7926484fb09</uuid>
			<name>Face&lt;1&gt;@zphr-aerod-5.1 cm Fin Can-v2_1&lt;1&gt;</name>
			<type>5</type>
			<id1>0</id1>
			<id2>0</id2>
			<update_stamp>0</update_stamp>
			<group>0</group>
			<geom_stamp_uuid>84c30ed2-3ea7-486a-a249-c94490be07c6</geom_stamp_uuid>
			<origin>
				<item>0.69199959471957406</item>
				<item>0.21764726210023522</item>
				<item>5.858048920948332</item>
			</origin>
			<normal>
				<item>-0.24264109091169866</item>
				<item>0.95450887333072465</item>
				<item>0.17331506493692747</item>
			</normal>
			<vector>
				<item>0.58123819371909613</item>
				<item>0</item>
				<item>0.81373347120673523</item>
			</vector>
			<pos>0</pos>
			<flip>1</flip>
			<min>-7.84225304143839</min>
			<max>9.7821242873018299</max>
			<curve_data>
				<start>0</start>
				<end>0</end>
				<length>0</length>
				<data/>
			</curve_data>
			<path>
				<path_elems/>
			</path>
		</item>
	</geom_ref>
	<domain_filter>
		<enabled>false</enabled>
		<keep>true</keep>
		<type>0</type>
		<domains/>
	</domain_filter>
	<contours>
		<display>true</display>
		<palette>
			<uuid>02d3efd2-5a0c-4fae-a49b-27e6bcbe46d5</uuid>
			<parameter>
				<uuid>46096123-A86C-43c8-B809-DB1C7CB2E6AA</uuid>
				<name/>
				<unit>0</unit>
				<formula/>
				<formula2/>
				<formula3/>
				<locality>0</locality>
			</parameter>
			<param_min>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_min>
			<param_max>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_max>
			<cs_uuid/>
			<cs_xform>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</cs_xform>
			<color_palette>5</color_palette>
			<ncolors>10</ncolors>
			<outer_minmax_coloring>0</outer_minmax_coloring>
			<outer_min_color>16711680</outer_min_color>
			<outer_max_color>255</outer_max_color>
			<outer_colors_display>false</outer_colors_display>
			<logarithmic>false</logarithmic>
			<custom_params_maxs>
				<46096123-A86C-43c8-B809-DB1C7CB2E6AA>
					<value>0</value>
					<is_initialized>false</is_initialized>
					<is_global>true</is_global>
					<is_plot>false</is_plot>
				</46096123-A86C-43c8-B809-DB1C7CB2E6AA>
			</custom_params_maxs>
			<custom_params_mins>
				<46096123-A86C-43c8-B809-DB1C7CB2E6AA>
					<value>0</value>
					<is_initialized>false</is_initialized>
					<is_global>true</is_global>
					<is_plot>false</is_plot>
				</46096123-A86C-43c8-B809-DB1C7CB2E6AA>
			</custom_params_mins>
			<cs_name>Global Coordinate System</cs_name>
			<display_plot_names>true</display_plot_names>
			<display_plot_minmaxes>false</display_plot_minmaxes>
			<display_title>false</display_title>
			<title/>
			<auto_scale_font>false</auto_scale_font>
			<use_default_font>true</use_default_font>
			<font>
				<name/>
				<size>9</size>
				<color>0</color>
				<font_isbold>false</font_isbold>
				<font_isitalic>false</font_isitalic>
			</font>
			<bkgd_color>16777215</bkgd_color>
			<bkgd_transp>1</bkgd_transp>
			<x>0</x>
			<y>0</y>
			<width>20</width>
			<height>200</height>
			<auto_ticks>true</auto_ticks>
			<ticks_number>11</ticks_number>
			<vertical>3</vertical>
			<rot_text>false</rot_text>
			<is_user_pos>false</is_user_pos>
		</palette>
		<color_by_param>true</color_by_param>
		<color>0</color>
	</contours>
	<min_callout>
		<display>false</display>
		<coordinates>false</coordinates>
		<appearance>
			<title>true</title>
			<title_source>0</title_source>
			<use_default_font>true</use_default_font>
			<font>
				<name/>
				<size>9</size>
				<color>0</color>
				<font_isbold>false</font_isbold>
				<font_isitalic>false</font_isitalic>
			</font>
			<value_color>16777215</value_color>
			<title_color>11711154</title_color>
			<line_color>0</line_color>
			<auto_line_color>true</auto_line_color>
			<transparency>0</transparency>
			<pinned>false</pinned>
			<show_results>true</show_results>
		</appearance>
		<position_initialized>false</position_initialized>
		<position>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</position>
	</min_callout>
	<max_callout>
		<display>false</display>
		<coordinates>false</coordinates>
		<appearance>
			<title>true</title>
			<title_source>0</title_source>
			<use_default_font>true</use_default_font>
			<font>
				<name/>
				<size>9</size>
				<color>0</color>
				<font_isbold>false</font_isbold>
				<font_isitalic>false</font_isitalic>
			</font>
			<value_color>16777215</value_color>
			<title_color>11711154</title_color>
			<line_color>0</line_color>
			<auto_line_color>true</auto_line_color>
			<transparency>0</transparency>
			<pinned>false</pinned>
			<show_results>true</show_results>
		</appearance>
		<position_initialized>false</position_initialized>
		<position>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</position>
	</max_callout>
	<isolines>
		<display>false</display>
		<palette>
			<uuid>5a7225f9-1c46-4b4f-9786-8b6051c1f79a</uuid>
			<parameter>
				<uuid/>
				<name/>
				<unit>0</unit>
				<formula/>
				<formula2/>
				<formula3/>
				<locality>0</locality>
			</parameter>
			<param_min>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_min>
			<param_max>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_max>
			<cs_uuid/>
			<cs_xform>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</cs_xform>
			<color_palette>5</color_palette>
			<ncolors>10</ncolors>
			<outer_minmax_coloring>0</outer_minmax_coloring>
			<outer_min_color>16711680</outer_min_color>
			<outer_max_color>255</outer_max_color>
			<outer_colors_display>false</outer_colors_display>
			<logarithmic>false</logarithmic>
			<custom_params_maxs/>
			<custom_params_mins/>
			<cs_name/>
			<display_plot_names>true</display_plot_names>
			<display_plot_minmaxes>false</display_plot_minmaxes>
			<display_title>false</display_title>
			<title/>
			<auto_scale_font>false</auto_scale_font>
			<use_default_font>true</use_default_font>
			<font>
				<name/>
				<size>9</size>
				<color>0</color>
				<font_isbold>false</font_isbold>
				<font_isitalic>false</font_isitalic>
			</font>
			<bkgd_color>16777215</bkgd_color>
			<bkgd_transp>1</bkgd_transp>
			<x>0</x>
			<y>0</y>
			<width>20</width>
			<height>200</height>
			<auto_ticks>true</auto_ticks>
			<ticks_number>11</ticks_number>
			<vertical>3</vertical>
			<rot_text>false</rot_text>
			<is_user_pos>false</is_user_pos>
		</palette>
		<width>1</width>
		<color_by_param>false</color_by_param>
		<color>0</color>
	</isolines>
	<vectors>
		<display>false</display>
		<build_palette>
			<uuid>62f8b8c5-8d28-4208-802d-50a0513649b8</uuid>
			<parameter>
				<uuid/>
				<name/>
				<unit>0</unit>
				<formula/>
				<formula2/>
				<formula3/>
				<locality>0</locality>
			</parameter>
			<param_min>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_min>
			<param_max>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_max>
			<cs_uuid/>
			<cs_xform>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</cs_xform>
			<color_palette>5</color_palette>
			<ncolors>10</ncolors>
			<outer_minmax_coloring>0</outer_minmax_coloring>
			<outer_min_color>16711680</outer_min_color>
			<outer_max_color>255</outer_max_color>
			<outer_colors_display>false</outer_colors_display>
			<logarithmic>false</logarithmic>
			<custom_params_maxs/>
			<custom_params_mins/>
			<cs_name/>
			<display_plot_names>true</display_plot_names>
			<display_plot_minmaxes>false</display_plot_minmaxes>
			<display_title>false</display_title>
			<title/>
			<auto_scale_font>false</auto_scale_font>
			<use_default_font>true</use_default_font>
			<font>
				<name/>
				<size>9</size>
				<color>0</color>
				<font_isbold>false</font_isbold>
				<font_isitalic>false</font_isitalic>
			</font>
			<bkgd_color>16777215</bkgd_color>
			<bkgd_transp>1</bkgd_transp>
			<x>0</x>
			<y>0</y>
			<width>20</width>
			<height>200</height>
			<auto_ticks>true</auto_ticks>
			<ticks_number>11</ticks_number>
			<vertical>3</vertical>
			<rot_text>false</rot_text>
			<is_user_pos>false</is_user_pos>
		</build_palette>
		<palette>
			<uuid>b223fb4c-984f-4cef-bd93-e4613861a9af</uuid>
			<parameter>
				<uuid/>
				<name/>
				<unit>0</unit>
				<formula/>
				<formula2/>
				<formula3/>
				<locality>0</locality>
			</parameter>
			<param_min>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_min>
			<param_max>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_max>
			<cs_uuid/>
			<cs_xform>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</cs_xform>
			<color_palette>5</color_palette>
			<ncolors>10</ncolors>
			<outer_minmax_coloring>0</outer_minmax_coloring>
			<outer_min_color>16711680</outer_min_color>
			<outer_max_color>255</outer_max_color>
			<outer_colors_display>false</outer_colors_display>
			<logarithmic>false</logarithmic>
			<custom_params_maxs/>
			<custom_params_mins/>
			<cs_name/>
			<display_plot_names>true</display_plot_names>
			<display_plot_minmaxes>false</display_plot_minmaxes>
			<display_title>false</display_title>
			<title/>
			<auto_scale_font>false</auto_scale_font>
			<use_default_font>true</use_default_font>
			<font>
				<name/>
				<size>9</size>
				<color>0</color>
				<font_isbold>false</font_isbold>
				<font_isitalic>false</font_isitalic>
			</font>
			<bkgd_color>16777215</bkgd_color>
			<bkgd_transp>1</bkgd_transp>
			<x>0</x>
			<y>0</y>
			<width>20</width>
			<height>200</height>
			<auto_ticks>true</auto_ticks>
			<ticks_number>11</ticks_number>
			<vertical>3</vertical>
			<rot_text>false</rot_text>
			<is_user_pos>false</is_user_pos>
		</palette>
		<color_by_param>false</color_by_param>
		<color>0</color>
		<vectors_projected>true</vectors_projected>
		<arrow_size>0.01</arrow_size>
		<spacing>0.01</spacing>
		<minmax_arrowsize_ratio>0.001</minmax_arrowsize_ratio>
		<logarithmic_arrows>false</logarithmic_arrows>
		<vistype>0</vistype>
		<dynamic>
			<enabled>false</enabled>
			<width>6</width>
			<arrow_size>32</arrow_size>
			<spacing>8</spacing>
		</dynamic>
	</vectors>
	<essslic>
		<display>false</display>
		<build_palette>
			<uuid>a792a3de-315c-478c-babf-01fd169ba5f2</uuid>
			<parameter>
				<uuid/>
				<name/>
				<unit>0</unit>
				<formula/>
				<formula2/>
				<formula3/>
				<locality>0</locality>
			</parameter>
			<param_min>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_min>
			<param_max>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_max>
			<cs_uuid/>
			<cs_xform>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</cs_xform>
			<color_palette>5</color_palette>
			<ncolors>10</ncolors>
			<outer_minmax_coloring>0</outer_minmax_coloring>
			<outer_min_color>16711680</outer_min_color>
			<outer_max_color>255</outer_max_color>
			<outer_colors_display>false</outer_colors_display>
			<logarithmic>false</logarithmic>
			<custom_params_maxs/>
			<custom_params_mins/>
			<cs_name/>
			<display_plot_names>true</display_plot_names>
			<display_plot_minmaxes>false</display_plot_minmaxes>
			<display_title>false</display_title>
			<title/>
			<auto_scale_font>false</auto_scale_font>
			<use_default_font>true</use_default_font>
			<font>
				<name/>
				<size>9</size>
				<color>0</color>
				<font_isbold>false</font_isbold>
				<font_isitalic>false</font_isitalic>
			</font>
			<bkgd_color>16777215</bkgd_color>
			<bkgd_transp>1</bkgd_transp>
			<x>0</x>
			<y>0</y>
			<width>20</width>
			<height>200</height>
			<auto_ticks>true</auto_ticks>
			<ticks_number>11</ticks_number>
			<vertical>3</vertical>
			<rot_text>false</rot_text>
			<is_user_pos>false</is_user_pos>
		</build_palette>
		<palette>
			<uuid>ece5464d-3dad-4d8e-ada4-dc71ccfe6199</uuid>
			<parameter>
				<uuid/>
				<name/>
				<unit>0</unit>
				<formula/>
				<formula2/>
				<formula3/>
				<locality>0</locality>
			</parameter>
			<param_min>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_min>
			<param_max>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_max>
			<cs_uuid/>
			<cs_xform>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</cs_xform>
			<color_palette>5</color_palette>
			<ncolors>10</ncolors>
			<outer_minmax_coloring>0</outer_minmax_coloring>
			<outer_min_color>16711680</outer_min_color>
			<outer_max_color>255</outer_max_color>
			<outer_colors_display>false</outer_colors_display>
			<logarithmic>false</logarithmic>
			<custom_params_maxs/>
			<custom_params_mins/>
			<cs_name/>
			<display_plot_names>true</display_plot_names>
			<display_plot_minmaxes>false</display_plot_minmaxes>
			<display_title>false</display_title>
			<title/>
			<auto_scale_font>false</auto_scale_font>
			<use_default_font>true</use_default_font>
			<font>
				<name/>
				<size>9</size>
				<color>0</color>
				<font_isbold>false</font_isbold>
				<font_isitalic>false</font_isitalic>
			</font>
			<bkgd_color>16777215</bkgd_color>
			<bkgd_transp>1</bkgd_transp>
			<x>0</x>
			<y>0</y>
			<width>20</width>
			<height>200</height>
			<auto_ticks>true</auto_ticks>
			<ticks_number>11</ticks_number>
			<vertical>3</vertical>
			<rot_text>false</rot_text>
			<is_user_pos>false</is_user_pos>
		</palette>
		<color_by_param>false</color_by_param>
		<color>0</color>
		<vistype>0</vistype>
		<esss_vistype>0</esss_vistype>
		<esss_linespacing>12</esss_linespacing>
		<esss_linewidth>2</esss_linewidth>
		<lic_noisegrainsize>1</lic_noisegrainsize>
		<lic_noisedensity>0.5</lic_noisedensity>
		<lic_contrast>0.10000000000000001</lic_contrast>
		<lic_convsize>64</lic_convsize>
	</essslic>
	<mesh>
		<display>true</display>
		<color>0</color>
	</mesh>
	<background>
		<display>false</display>
		<color>16777215</color>
	</background>
	<outlines_display>true</outlines_display>
	<outlines_color>0</outlines_color>
	<DeformedShape>
		<uuid>8f6268f6-f4dd-483e-a978-e7497aed463d</uuid>
		<creation_date>1757096166</creation_date>
		<enabled>false</enabled>
		<auto_scale>true</auto_scale>
		<scale/>
		<mode>-1</mode>
	</DeformedShape>
	<medias>
		<item>1</item>
	</medias>
	<mesh_type>0</mesh_type>
	<MeshTypePriority>0</MeshTypePriority>
	<use_offset>false</use_offset>
	<MediaPriority>1</MediaPriority>
</feature>
