<?xml version="1.0" encoding="utf-8"?>
<feature>
	<version>1</version>
	<uuid/>
	<name>Global Min/Max: ShortCut Number</name>
	<type>13</type>
	<res_file_key>442db3e4-ab0e-4697-a117-a061b5db8a9d</res_file_key>
	<cs_name/>
	<cs_uuid/>
	<x_form>
		<global>true</global>
		<origin>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</origin>
		<translate>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
		</translate>
	</x_form>
	<display_bl>false</display_bl>
	<interpolate>true</interpolate>
	<use_cad_geom>false</use_cad_geom>
	<moving_reference>true</moving_reference>
	<moving_display>true</moving_display>
	<full_task>false</full_task>
	<use_in_BRP>false</use_in_BRP>
	<parameter>
		<uuid>8098535E-9417-4fd7-9B7D-03A131E6F20B</uuid>
		<name>ShortCut Number</name>
		<unit>42</unit>
		<formula/>
		<formula2/>
		<formula3/>
		<locality>0</locality>
	</parameter>
</feature>
