<?xml version="1.0" encoding="utf-8"?>
<feature>
	<version>2</version>
	<uuid>d22289cd-4476-43b4-8b22-b388619f3c40</uuid>
	<name>Goal Plot 1</name>
	<type>3</type>
	<res_file_key>a2f6edaf-678b-4417-b1ac-17adc7a25817</res_file_key>
	<cs_name/>
	<cs_uuid/>
	<x_form>
		<global>true</global>
		<origin>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</origin>
		<translate>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
		</translate>
	</x_form>
	<display_bl>false</display_bl>
	<interpolate>true</interpolate>
	<use_cad_geom>false</use_cad_geom>
	<moving_reference>true</moving_reference>
	<moving_display>true</moving_display>
	<full_task>false</full_task>
	<use_in_BRP>false</use_in_BRP>
	<transparency>0</transparency>
	<palette>
		<uuid>6d475975-60ef-4f23-bb7f-58b9becbafd8</uuid>
		<parameter>
			<uuid/>
			<name/>
			<unit>0</unit>
			<formula/>
			<formula2/>
			<formula3/>
			<locality>0</locality>
		</parameter>
		<param_min>
			<value>0</value>
			<is_initialized>false</is_initialized>
			<is_global>true</is_global>
			<is_plot>false</is_plot>
		</param_min>
		<param_max>
			<value>0</value>
			<is_initialized>false</is_initialized>
			<is_global>true</is_global>
			<is_plot>false</is_plot>
		</param_max>
		<cs_uuid/>
		<cs_xform>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</cs_xform>
		<color_palette>5</color_palette>
		<ncolors>10</ncolors>
		<outer_minmax_coloring>0</outer_minmax_coloring>
		<outer_min_color>16711680</outer_min_color>
		<outer_max_color>255</outer_max_color>
		<outer_colors_display>false</outer_colors_display>
		<logarithmic>false</logarithmic>
		<custom_params_maxs/>
		<custom_params_mins/>
		<cs_name/>
		<display_plot_names>true</display_plot_names>
		<display_plot_minmaxes>false</display_plot_minmaxes>
		<display_title>false</display_title>
		<title/>
		<auto_scale_font>false</auto_scale_font>
		<use_default_font>true</use_default_font>
		<font>
			<name/>
			<size>9</size>
			<color>0</color>
			<font_isbold>false</font_isbold>
			<font_isitalic>false</font_isitalic>
		</font>
		<bkgd_color>16777215</bkgd_color>
		<bkgd_transp>1</bkgd_transp>
		<x>0</x>
		<y>0</y>
		<width>20</width>
		<height>200</height>
		<auto_ticks>true</auto_ticks>
		<ticks_number>11</ticks_number>
		<vertical>3</vertical>
		<rot_text>false</rot_text>
		<is_user_pos>false</is_user_pos>
	</palette>
	<chart/>
	<minmax>
		<x_min>
			<value>0</value>
			<fit>true</fit>
		</x_min>
		<x_max>
			<value>0</value>
			<fit>true</fit>
		</x_max>
		<y_min>
			<value>0</value>
			<fit>true</fit>
		</y_min>
		<y_max>
			<value>0</value>
			<fit>true</fit>
		</y_max>
	</minmax>
	<appearance>
		<font>
			<name>Arial</name>
			<size>9</size>
			<color>0</color>
			<font_isbold>false</font_isbold>
			<font_isitalic>false</font_isitalic>
		</font>
		<use_default_font>true</use_default_font>
		<transparency>1</transparency>
		<background_color>0</background_color>
		<position>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</position>
		<scale_color>6579300</scale_color>
		<display_plot_names>true</display_plot_names>
	</appearance>
	<use_all_faces>false</use_all_faces>
	<geom_ref/>
	<group_by_param>false</group_by_param>
	<abscissa>1</abscissa>
	<goal_name/>
	<goal_uuid/>
	<goal_data>
		<item>
			<map_key>618c5cd8-bd7c-44bc-9fc7-77e4b5cefdf3</map_key>
			<formula/>
			<unit>14</unit>
			<goal_ui_order>0</goal_ui_order>
		</item>
		<item>
			<map_key>77b30db0-879f-4f1a-a335-d6692220cff5</map_key>
			<formula/>
			<unit>33</unit>
			<goal_ui_order>1</goal_ui_order>
		</item>
		<item>
			<map_key>1ca1a7fd-4441-4a87-8d99-ef1531ac27d1</map_key>
			<formula/>
			<unit>7</unit>
			<goal_ui_order>2</goal_ui_order>
		</item>
		<item>
			<map_key>a925b3a0-75ea-408a-91e1-2660f92b2908</map_key>
			<formula/>
			<unit>7</unit>
			<goal_ui_order>3</goal_ui_order>
		</item>
		<item>
			<map_key>51546d1c-c9bd-41c6-b33e-a2bb6f3420df</map_key>
			<formula/>
			<unit>7</unit>
			<goal_ui_order>4</goal_ui_order>
		</item>
		<item>
			<map_key>3128d24a-27af-4ab8-8b0f-75678cf5ee9c</map_key>
			<formula/>
			<unit>7</unit>
			<goal_ui_order>5</goal_ui_order>
		</item>
		<item>
			<map_key>c328ad6d-235d-487b-ae4d-2d309e10a89c</map_key>
			<formula/>
			<unit>14</unit>
			<goal_ui_order>7</goal_ui_order>
		</item>
		<item>
			<map_key>1e3f1c2d-cd4b-4ee0-979f-f0226b4f2b44</map_key>
			<formula/>
			<unit>14</unit>
			<goal_ui_order>6</goal_ui_order>
		</item>
		<item>
			<map_key>847a6d2f-f9ef-4a01-813f-54bfc657f69e</map_key>
			<formula/>
			<unit>14</unit>
			<goal_ui_order>8</goal_ui_order>
		</item>
		<item>
			<map_key>b2640b51-e251-4265-ab65-fa53fbbda557</map_key>
			<formula/>
			<unit>14</unit>
			<goal_ui_order>9</goal_ui_order>
		</item>
	</goal_data>
	<unit_definition>
		<item>
			<map_key>14</map_key>
			<unit_def_custom_name/>
			<unit_def_custom_si_to_unit/>
			<unit_def_custom_unit_to_si/>
			<unit_def_precision>2</unit_def_precision>
			<unit_def_system>1200</unit_def_system>
		</item>
		<item>
			<map_key>33</map_key>
			<unit_def_custom_name/>
			<unit_def_custom_si_to_unit/>
			<unit_def_custom_unit_to_si/>
			<unit_def_precision>2</unit_def_precision>
			<unit_def_system>3000</unit_def_system>
		</item>
		<item>
			<map_key>7</map_key>
			<unit_def_custom_name/>
			<unit_def_custom_si_to_unit/>
			<unit_def_custom_unit_to_si/>
			<unit_def_precision>3</unit_def_precision>
			<unit_def_system>1100</unit_def_system>
		</item>
	</unit_definition>
	<goal_data_eq_goals_present>false</goal_data_eq_goals_present>
	<iteration>-1</iteration>
	<time>-1</time>
	<limit_by_iter>true</limit_by_iter>
	<limit_iter>995</limit_iter>
	<display>0</display>
	<callout>
		<position_initialized>0</position_initialized>
		<position>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</position>
		<2d_position>
			<item>0</item>
			<item>0</item>
		</2d_position>
		<visibility>true</visibility>
		<appearance>
			<title>true</title>
			<title_source>0</title_source>
			<use_default_font>true</use_default_font>
			<font>
				<name>Arial</name>
				<size>9</size>
				<color>0</color>
				<font_isbold>false</font_isbold>
				<font_isitalic>false</font_isitalic>
			</font>
			<value_color>16777215</value_color>
			<title_color>11711154</title_color>
			<line_color>0</line_color>
			<auto_line_color>true</auto_line_color>
			<transparency>0</transparency>
			<pinned>false</pinned>
			<show_results>true</show_results>
		</appearance>
	</callout>
</feature>
