<?xml version="1.0" encoding="utf-8"?>
<feature>
	<version>1</version>
	<uuid>f0b4c7a3-5386-4887-bab4-247f6222f045</uuid>
	<name>Scene 1</name>
	<type>33</type>
	<res_file_key>1634ab93-c1f2-473e-9dd0-a2bf8c0131c7</res_file_key>
	<cs_name/>
	<cs_uuid/>
	<x_form>
		<global>true</global>
		<origin>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</origin>
		<translate>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
		</translate>
	</x_form>
	<display_bl>false</display_bl>
	<interpolate>true</interpolate>
	<use_cad_geom>false</use_cad_geom>
	<moving_reference>true</moving_reference>
	<moving_display>true</moving_display>
	<full_task>false</full_task>
	<use_in_BRP>false</use_in_BRP>
	<name_template/>
	<scene_description>
		<light_sources>
			<item>
				<type>0</type>
				<color>16777215</color>
				<ambient>0.300000012</ambient>
				<diffuse>0.800000012</diffuse>
				<specular>0.200000003</specular>
				<position>
					<item>0</item>
					<item>0</item>
					<item>0</item>
				</position>
				<locked_to_model>true</locked_to_model>
				<SpotDirection>
					<item>0</item>
					<item>0</item>
					<item>0</item>
				</SpotDirection>
				<SpotCutoff>180</SpotCutoff>
				<SpotAtt0>1</SpotAtt0>
				<SpotAtt1>0</SpotAtt1>
				<SpotAtt2>0</SpotAtt2>
				<SpotExp>0</SpotExp>
			</item>
			<item>
				<type>1</type>
				<color>16777215</color>
				<ambient>0.100000001</ambient>
				<diffuse>0.300000012</diffuse>
				<specular>0.300000012</specular>
				<position>
					<item>7.0999999</item>
					<item>7.0999999</item>
					<item>0</item>
				</position>
				<locked_to_model>true</locked_to_model>
				<SpotDirection>
					<item>0</item>
					<item>0</item>
					<item>0</item>
				</SpotDirection>
				<SpotCutoff>180</SpotCutoff>
				<SpotAtt0>1</SpotAtt0>
				<SpotAtt1>0</SpotAtt1>
				<SpotAtt2>0</SpotAtt2>
				<SpotExp>0</SpotExp>
			</item>
			<item>
				<type>1</type>
				<color>16777215</color>
				<ambient>0</ambient>
				<diffuse>0.100000001</diffuse>
				<specular>0.300000012</specular>
				<position>
					<item>-3.4000001</item>
					<item>6.0999999</item>
					<item>-7.0999999</item>
				</position>
				<locked_to_model>true</locked_to_model>
				<SpotDirection>
					<item>0</item>
					<item>0</item>
					<item>0</item>
				</SpotDirection>
				<SpotCutoff>180</SpotCutoff>
				<SpotAtt0>1</SpotAtt0>
				<SpotAtt1>0</SpotAtt1>
				<SpotAtt2>0</SpotAtt2>
				<SpotExp>0</SpotExp>
			</item>
			<item>
				<type>1</type>
				<color>16777215</color>
				<ambient>0</ambient>
				<diffuse>0.200000003</diffuse>
				<specular>0.300000012</specular>
				<position>
					<item>-9.19999981</item>
					<item>3.4000001</item>
					<item>-1.79999995</item>
				</position>
				<locked_to_model>true</locked_to_model>
				<SpotDirection>
					<item>0</item>
					<item>0</item>
					<item>0</item>
				</SpotDirection>
				<SpotCutoff>180</SpotCutoff>
				<SpotAtt0>1</SpotAtt0>
				<SpotAtt1>0</SpotAtt1>
				<SpotAtt2>0</SpotAtt2>
				<SpotExp>0</SpotExp>
			</item>
		</light_sources>
		<bkgd_color>4276545</bkgd_color>
		<bkgd_bottom_color>4276545</bkgd_bottom_color>
		<orientation>
			<matrix>
				<item>0.78396681168255689</item>
				<item>-0.29116781673407122</item>
				<item>-0.54828582024214401</item>
				<item>0</item>
				<item>2.7235158572835871e-16</item>
				<item>0.88318847135431711</item>
				<item>-0.46901825557948629</item>
				<item>0</item>
				<item>0.62080273693040866</item>
				<item>0.36769474644756439</item>
				<item>0.69239045000243538</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
			</matrix>
			<position>
				<item>-39.269572158149437</item>
				<item>-30.653223737578625</item>
				<item>17.326494415109423</item>
			</position>
			<align>
				<item>0.68320097528553492</item>
				<item>0.98437944368511587</item>
				<item>1.4580389721788456</item>
			</align>
			<scale>25.047557742564948</scale>
			<aspect>1.5600976205003034</aspect>
		</orientation>
		<display>5</display>
		<model_appearance>
			<components>
				<item>
					<name>KST X06-1</name>
					<color>12632256</color>
					<transparency>1</transparency>
					<display>false</display>
				</item>
				<item>
					<name>KST X06-1/KST X06.stp-1</name>
					<color>12632256</color>
					<transparency>1</transparency>
					<display>true</display>
				</item>
				<item>
					<name>KST X06-1/KST X06.stp-1/KST06 Body_2.stp-1</name>
					<color>15651274</color>
					<transparency>1</transparency>
					<display>true</display>
				</item>
				<item>
					<name>zphr-aerod-5.1 cm Fin Can-v2_1-1</name>
					<color>15717067</color>
					<transparency>1</transparency>
					<display>true</display>
				</item>
				<item>
					<name>zphr-aerod-Control Surface -v2_1-1</name>
					<color>12536611</color>
					<transparency>1</transparency>
					<display>true</display>
				</item>
				<item>
					<name>zphr-aerod-Control Surface -v2_1-2</name>
					<color>12536611</color>
					<transparency>1</transparency>
					<display>true</display>
				</item>
			</components>
		</model_appearance>
		<section_planes>
			<section_plane/>
			<ShowCap>true</ShowCap>
			<CustomCapColor>true</CustomCapColor>
		</section_planes>
		<render_mode>0</render_mode>
		<std_views_scheme>0</std_views_scheme>
		<visibility>
			<item>true</item>
			<item>true</item>
			<item>true</item>
			<item>true</item>
			<item>true</item>
			<item>true</item>
			<item>true</item>
			<item>true</item>
			<item>false</item>
			<item>false</item>
			<item>false</item>
			<item>false</item>
			<item>true</item>
			<item>false</item>
			<item>false</item>
			<item>false</item>
		</visibility>
		<computational_domain>
			<line_color>0</line_color>
			<color>0</color>
			<transparency>0.100000024</transparency>
		</computational_domain>
		<callouts/>
		<probes_callouts/>
		<plots>
			<item>fe85452a-0452-4374-8224-f3b31e4834cb</item>
		</plots>
		<plots_visibility/>
		<time>
			<title/>
			<values>
				<item>Iteration = 104</item>
			</values>
			<position>
				<item>1530</item>
				<item>48</item>
			</position>
			<appearance>
				<font>
					<name>Arial</name>
					<size>9</size>
					<color>0</color>
					<font_isbold>false</font_isbold>
					<font_isitalic>false</font_isitalic>
				</font>
				<use_default_font>true</use_default_font>
				<transparency>1</transparency>
				<background_color>0</background_color>
				<position>
					<item>0</item>
					<item>0</item>
					<item>0</item>
					<item>0</item>
				</position>
				<scale_color>6579300</scale_color>
				<display_plot_names>true</display_plot_names>
			</appearance>
			<icon>0</icon>
			<select_color>16711680</select_color>
			<highlight_color>255</highlight_color>
		</time>
		<gmm_pos_parameter/>
		<global_min_max>
			<font>
				<name/>
				<size>9</size>
				<color>0</color>
				<font_isbold>false</font_isbold>
				<font_isitalic>false</font_isitalic>
			</font>
			<use_default_font>true</use_default_font>
			<transparency>1</transparency>
			<background_color>16777215</background_color>
			<position>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</position>
			<min>
				<callout>
					<title>true</title>
					<title_source>0</title_source>
					<use_default_font>true</use_default_font>
					<font>
						<name/>
						<size>9</size>
						<color>0</color>
						<font_isbold>false</font_isbold>
						<font_isitalic>false</font_isitalic>
					</font>
					<value_color>16777215</value_color>
					<title_color>11711154</title_color>
					<line_color>0</line_color>
					<auto_line_color>true</auto_line_color>
					<transparency>0</transparency>
					<pinned>false</pinned>
					<show_results>true</show_results>
				</callout>
			</min>
			<max>
				<callout>
					<title>true</title>
					<title_source>0</title_source>
					<use_default_font>true</use_default_font>
					<font>
						<name/>
						<size>9</size>
						<color>0</color>
						<font_isbold>false</font_isbold>
						<font_isitalic>false</font_isitalic>
					</font>
					<value_color>16777215</value_color>
					<title_color>11711154</title_color>
					<line_color>0</line_color>
					<auto_line_color>true</auto_line_color>
					<transparency>0</transparency>
					<pinned>false</pinned>
					<show_results>true</show_results>
				</callout>
			</max>
		</global_min_max>
		<position>
			<min_callout>
				<type>1</type>
				<position>
					<item>0</item>
					<item>0</item>
					<item>0</item>
				</position>
				<2d_position>
					<item>0</item>
					<item>0</item>
				</2d_position>
			</min_callout>
			<max_callout>
				<type>1</type>
				<position>
					<item>0</item>
					<item>0</item>
					<item>0</item>
				</position>
				<2d_position>
					<item>0</item>
					<item>0</item>
				</2d_position>
			</max_callout>
		</position>
		<result_type>2</result_type>
		<cpt/>
		<fld/>
		<watermark>
			<text/>
		</watermark>
		<2druller>
			<rect>
				<item>-3.64327121</item>
				<item>3.80580974</item>
				<item>-3.87770104</item>
				<item>3.5713799</item>
			</rect>
			<margins>
				<item>220</item>
				<item>70</item>
				<item>25</item>
				<item>50</item>
			</margins>
			<grid_step>
				<item>0.100000001</item>
				<item>0.100000001</item>
			</grid_step>
			<display_grid>true</display_grid>
			<display_values>true</display_values>
			<ruller_color>16711680</ruller_color>
			<grid_color>4993843</grid_color>
			<font_color>0</font_color>
			<ruller_transparency>1</ruller_transparency>
			<grid_transparency>0.300000012</grid_transparency>
			<font_transparency>1</font_transparency>
			<scale>0.0500000007</scale>
			<font_size>15</font_size>
			<mode>1</mode>
			<ticks_number>
				<item>10</item>
				<item>10</item>
			</ticks_number>
		</2druller>
		<3druller>
			<box_display>true</box_display>
			<box_color>16711680</box_color>
			<box_transparency>0.899999976</box_transparency>
			<display_grid>true</display_grid>
			<grid_display_side>
				<item>true</item>
				<item>false</item>
				<item>true</item>
				<item>false</item>
				<item>true</item>
				<item>false</item>
			</grid_display_side>
			<grid_color>3381632</grid_color>
			<grid_transparency>0.300000012</grid_transparency>
			<grid_captions_display>false</grid_captions_display>
			<grid_captions_color>0</grid_captions_color>
			<grid_captions_transparency>0.5</grid_captions_transparency>
			<grid_captions_font_height>0.0500000007</grid_captions_font_height>
			<xyz_captions_display>false</xyz_captions_display>
			<xyz_captions_color>0</xyz_captions_color>
			<xyz_captions_transparency>1</xyz_captions_transparency>
			<xyz_captions_font_height>0.0799999982</xyz_captions_font_height>
			<grid_step>
				<item>0.100000001</item>
				<item>0.100000001</item>
				<item>0.100000001</item>
			</grid_step>
		</3druller>
		<camera>
			<origin>
				<item>0.70348903057409817</item>
				<item>0.94415476716614977</item>
				<item>1.6192806532743447</item>
			</origin>
			<up>
				<item>-0.29116781673407127</item>
				<item>0.88318847135431733</item>
				<item>0.36769474644756445</item>
			</up>
			<direction>
				<item>0.5482858202421439</item>
				<item>0.46901825557948634</item>
				<item>-0.69239045000243549</item>
			</direction>
			<scale>0.08130963140384169</scale>
		</camera>
	</scene_description>
	<features>
		<item>
			<type>1</type>
			<data>
				<uuid>fe85452a-0452-4374-8224-f3b31e4834cb</uuid>
				<name>Surface Plot 1</name>
				<type>1</type>
				<res_file_key>2092ad39-2bf2-4368-9918-88b135eeb584</res_file_key>
				<cs_name/>
				<cs_uuid/>
				<x_form>
					<global>true</global>
					<origin>
						<item>0</item>
						<item>0</item>
						<item>0</item>
					</origin>
					<translate>
						<item>1</item>
						<item>0</item>
						<item>0</item>
						<item>0</item>
						<item>1</item>
						<item>0</item>
						<item>0</item>
						<item>0</item>
						<item>1</item>
					</translate>
				</x_form>
				<display_bl>false</display_bl>
				<interpolate>true</interpolate>
				<use_cad_geom>true</use_cad_geom>
				<moving_reference>true</moving_reference>
				<moving_display>true</moving_display>
				<full_task>false</full_task>
				<use_in_BRP>false</use_in_BRP>
				<transparency>0</transparency>
				<box>
					<item>0.50789906454773559</item>
					<item>0.86092517893782805</item>
					<item>-0.0019205563148836369</item>
					<item>1.9706794436851154</item>
					<item>1.475124288758642</item>
					<item>2.9119269961679071</item>
				</box>
				<crop_region_anchors>
					<item>false</item>
					<item>false</item>
					<item>false</item>
					<item>false</item>
					<item>false</item>
					<item>false</item>
				</crop_region_anchors>
				<section_plane/>
				<use_all_faces>false</use_all_faces>
				<geom_ref>
					<item>
						<uuid>92918bd5-8408-4d52-b29b-682ebfbfbc88</uuid>
						<name>Face&lt;1&gt;@zphr-aerod-Control Surface -v2_1&lt;1&gt;</name>
						<type>5</type>
						<id1>0</id1>
						<id2>0</id2>
						<update_stamp>0</update_stamp>
						<group>-1</group>
						<geom_stamp_uuid>50a94030-af17-45cb-8c6a-3fee13f26923</geom_stamp_uuid>
						<origin>
							<item>0.68441212174278188</item>
							<item>0.9767857006891425</item>
							<item>2.1935256424632743</item>
						</origin>
						<normal>
							<item>-0.069098240146133458</item>
							<item>-0.99756405025982431</item>
							<item>-0.0095602739459779307</item>
						</normal>
						<vector>
							<item>-0.00033070183902041296</item>
							<item>-0.0095602739459779325</item>
							<item>0.99995424485241913</item>
						</vector>
						<pos>0</pos>
						<flip>1</flip>
						<min>-1.0105375231505289</min>
						<max>0.99538703311113796</max>
						<curve_data>
							<start>0</start>
							<end>0</end>
							<length>0</length>
							<data/>
						</curve_data>
						<path>
							<path_elems/>
						</path>
					</item>
				</geom_ref>
				<domain_filter>
					<enabled>false</enabled>
					<keep>true</keep>
					<type>0</type>
					<domains/>
				</domain_filter>
				<contours>
					<display>true</display>
					<palette>
						<uuid>3b842605-dfbf-4139-978a-6e451c70f81d</uuid>
						<parameter>
							<uuid>88A4B00C-3C32-4822-94C2-4682145D4F95</uuid>
							<name>Pressure</name>
							<unit>14</unit>
							<formula/>
							<formula2/>
							<formula3/>
							<locality>0</locality>
						</parameter>
						<param_min>
							<value>100842.39007741267</value>
							<is_initialized>true</is_initialized>
							<is_global>true</is_global>
							<is_plot>false</is_plot>
						</param_min>
						<param_max>
							<value>102730.07982447979</value>
							<is_initialized>true</is_initialized>
							<is_global>true</is_global>
							<is_plot>false</is_plot>
						</param_max>
						<cs_uuid/>
						<cs_xform>
							<item>1</item>
							<item>0</item>
							<item>0</item>
							<item>0</item>
							<item>1</item>
							<item>0</item>
							<item>0</item>
							<item>0</item>
							<item>1</item>
							<item>0</item>
							<item>0</item>
							<item>0</item>
							<item>1</item>
							<item>0</item>
							<item>0</item>
							<item>0</item>
						</cs_xform>
						<color_palette>5</color_palette>
						<ncolors>16</ncolors>
						<outer_minmax_coloring>0</outer_minmax_coloring>
						<outer_min_color>16711680</outer_min_color>
						<outer_max_color>255</outer_max_color>
						<outer_colors_display>true</outer_colors_display>
						<logarithmic>false</logarithmic>
						<custom_params_maxs>
							<88A4B00C-3C32-4822-94C2-4682145D4F95>
								<value>102730.07982447979</value>
								<is_initialized>true</is_initialized>
								<is_global>true</is_global>
								<is_plot>false</is_plot>
							</88A4B00C-3C32-4822-94C2-4682145D4F95>
						</custom_params_maxs>
						<custom_params_mins>
							<88A4B00C-3C32-4822-94C2-4682145D4F95>
								<value>100842.39007741267</value>
								<is_initialized>true</is_initialized>
								<is_global>true</is_global>
								<is_plot>false</is_plot>
							</88A4B00C-3C32-4822-94C2-4682145D4F95>
						</custom_params_mins>
						<cs_name>Global Coordinate System</cs_name>
						<display_plot_names>true</display_plot_names>
						<display_plot_minmaxes>false</display_plot_minmaxes>
						<display_title>false</display_title>
						<title/>
						<auto_scale_font>false</auto_scale_font>
						<use_default_font>true</use_default_font>
						<font>
							<name>Arial</name>
							<size>9</size>
							<color>0</color>
							<font_isbold>false</font_isbold>
							<font_isitalic>false</font_isitalic>
						</font>
						<bkgd_color>16777215</bkgd_color>
						<bkgd_transp>1</bkgd_transp>
						<x>488</x>
						<y>38</y>
						<width>20</width>
						<height>200</height>
						<auto_ticks>true</auto_ticks>
						<ticks_number>11</ticks_number>
						<vertical>3</vertical>
						<rot_text>false</rot_text>
						<is_user_pos>false</is_user_pos>
					</palette>
					<color_by_param>true</color_by_param>
					<color>16711680</color>
				</contours>
				<min_callout>
					<display>false</display>
					<coordinates>false</coordinates>
					<appearance>
						<title>true</title>
						<title_source>0</title_source>
						<use_default_font>true</use_default_font>
						<font>
							<name/>
							<size>9</size>
							<color>0</color>
							<font_isbold>false</font_isbold>
							<font_isitalic>false</font_isitalic>
						</font>
						<value_color>16777215</value_color>
						<title_color>16758122</title_color>
						<line_color>0</line_color>
						<auto_line_color>true</auto_line_color>
						<transparency>0</transparency>
						<pinned>false</pinned>
						<show_results>true</show_results>
					</appearance>
					<position_initialized>false</position_initialized>
					<position>
						<item>0</item>
						<item>0</item>
						<item>0</item>
					</position>
				</min_callout>
				<max_callout>
					<display>false</display>
					<coordinates>false</coordinates>
					<appearance>
						<title>true</title>
						<title_source>0</title_source>
						<use_default_font>true</use_default_font>
						<font>
							<name/>
							<size>9</size>
							<color>0</color>
							<font_isbold>false</font_isbold>
							<font_isitalic>false</font_isitalic>
						</font>
						<value_color>16777215</value_color>
						<title_color>8026879</title_color>
						<line_color>0</line_color>
						<auto_line_color>true</auto_line_color>
						<transparency>0</transparency>
						<pinned>false</pinned>
						<show_results>true</show_results>
					</appearance>
					<position_initialized>false</position_initialized>
					<position>
						<item>0</item>
						<item>0</item>
						<item>0</item>
					</position>
				</max_callout>
				<isolines>
					<display>false</display>
					<palette>
						<uuid>8990731f-264f-49c2-a158-5e2da04f94f9</uuid>
						<parameter>
							<uuid>88A4B00C-3C32-4822-94C2-4682145D4F95</uuid>
							<name>Pressure</name>
							<unit>14</unit>
							<formula/>
							<formula2/>
							<formula3/>
							<locality>0</locality>
						</parameter>
						<param_min>
							<value>100842.39007741267</value>
							<is_initialized>true</is_initialized>
							<is_global>true</is_global>
							<is_plot>false</is_plot>
						</param_min>
						<param_max>
							<value>102730.07982447979</value>
							<is_initialized>true</is_initialized>
							<is_global>true</is_global>
							<is_plot>false</is_plot>
						</param_max>
						<cs_uuid/>
						<cs_xform>
							<item>1</item>
							<item>0</item>
							<item>0</item>
							<item>0</item>
							<item>1</item>
							<item>0</item>
							<item>0</item>
							<item>0</item>
							<item>1</item>
							<item>0</item>
							<item>0</item>
							<item>0</item>
							<item>1</item>
							<item>0</item>
							<item>0</item>
							<item>0</item>
						</cs_xform>
						<color_palette>5</color_palette>
						<ncolors>9</ncolors>
						<outer_minmax_coloring>0</outer_minmax_coloring>
						<outer_min_color>16711680</outer_min_color>
						<outer_max_color>255</outer_max_color>
						<outer_colors_display>true</outer_colors_display>
						<logarithmic>false</logarithmic>
						<custom_params_maxs>
							<88A4B00C-3C32-4822-94C2-4682145D4F95>
								<value>102730.07982447979</value>
								<is_initialized>true</is_initialized>
								<is_global>true</is_global>
								<is_plot>false</is_plot>
							</88A4B00C-3C32-4822-94C2-4682145D4F95>
						</custom_params_maxs>
						<custom_params_mins>
							<88A4B00C-3C32-4822-94C2-4682145D4F95>
								<value>100842.39007741267</value>
								<is_initialized>true</is_initialized>
								<is_global>true</is_global>
								<is_plot>false</is_plot>
							</88A4B00C-3C32-4822-94C2-4682145D4F95>
						</custom_params_mins>
						<cs_name/>
						<display_plot_names>true</display_plot_names>
						<display_plot_minmaxes>false</display_plot_minmaxes>
						<display_title>false</display_title>
						<title/>
						<auto_scale_font>false</auto_scale_font>
						<use_default_font>true</use_default_font>
						<font>
							<name>Arial</name>
							<size>9</size>
							<color>0</color>
							<font_isbold>false</font_isbold>
							<font_isitalic>false</font_isitalic>
						</font>
						<bkgd_color>16777215</bkgd_color>
						<bkgd_transp>1</bkgd_transp>
						<x>488</x>
						<y>38</y>
						<width>20</width>
						<height>200</height>
						<auto_ticks>true</auto_ticks>
						<ticks_number>11</ticks_number>
						<vertical>3</vertical>
						<rot_text>false</rot_text>
						<is_user_pos>true</is_user_pos>
					</palette>
					<width>1</width>
					<color_by_param>true</color_by_param>
					<color>0</color>
				</isolines>
				<vectors>
					<display>false</display>
					<build_palette>
						<uuid>2c72b181-914f-4475-872d-5160d155032b</uuid>
						<parameter>
							<uuid>8A88FD9A-C36E-4151-864A-F5BC1C916074</uuid>
							<name/>
							<unit>0</unit>
							<formula/>
							<formula2/>
							<formula3/>
							<locality>0</locality>
						</parameter>
						<param_min>
							<value>0</value>
							<is_initialized>false</is_initialized>
							<is_global>true</is_global>
							<is_plot>false</is_plot>
						</param_min>
						<param_max>
							<value>0</value>
							<is_initialized>false</is_initialized>
							<is_global>true</is_global>
							<is_plot>false</is_plot>
						</param_max>
						<cs_uuid/>
						<cs_xform>
							<item>1</item>
							<item>0</item>
							<item>0</item>
							<item>0</item>
							<item>1</item>
							<item>0</item>
							<item>0</item>
							<item>0</item>
							<item>1</item>
							<item>0</item>
							<item>0</item>
							<item>0</item>
							<item>1</item>
							<item>0</item>
							<item>0</item>
							<item>0</item>
						</cs_xform>
						<color_palette>5</color_palette>
						<ncolors>10</ncolors>
						<outer_minmax_coloring>0</outer_minmax_coloring>
						<outer_min_color>16711680</outer_min_color>
						<outer_max_color>255</outer_max_color>
						<outer_colors_display>false</outer_colors_display>
						<logarithmic>false</logarithmic>
						<custom_params_maxs/>
						<custom_params_mins/>
						<cs_name/>
						<display_plot_names>true</display_plot_names>
						<display_plot_minmaxes>false</display_plot_minmaxes>
						<display_title>false</display_title>
						<title/>
						<auto_scale_font>false</auto_scale_font>
						<use_default_font>true</use_default_font>
						<font>
							<name/>
							<size>9</size>
							<color>0</color>
							<font_isbold>false</font_isbold>
							<font_isitalic>false</font_isitalic>
						</font>
						<bkgd_color>16777215</bkgd_color>
						<bkgd_transp>1</bkgd_transp>
						<x>0</x>
						<y>0</y>
						<width>20</width>
						<height>200</height>
						<auto_ticks>true</auto_ticks>
						<ticks_number>11</ticks_number>
						<vertical>3</vertical>
						<rot_text>false</rot_text>
						<is_user_pos>false</is_user_pos>
					</build_palette>
					<palette>
						<uuid>8990731f-264f-49c2-a158-5e2da04f94f9</uuid>
						<parameter>
							<uuid>88A4B00C-3C32-4822-94C2-4682145D4F95</uuid>
							<name>Pressure</name>
							<unit>14</unit>
							<formula/>
							<formula2/>
							<formula3/>
							<locality>0</locality>
						</parameter>
						<param_min>
							<value>100842.39007741267</value>
							<is_initialized>true</is_initialized>
							<is_global>true</is_global>
							<is_plot>false</is_plot>
						</param_min>
						<param_max>
							<value>102730.07982447979</value>
							<is_initialized>true</is_initialized>
							<is_global>true</is_global>
							<is_plot>false</is_plot>
						</param_max>
						<cs_uuid/>
						<cs_xform>
							<item>1</item>
							<item>0</item>
							<item>0</item>
							<item>0</item>
							<item>1</item>
							<item>0</item>
							<item>0</item>
							<item>0</item>
							<item>1</item>
							<item>0</item>
							<item>0</item>
							<item>0</item>
							<item>1</item>
							<item>0</item>
							<item>0</item>
							<item>0</item>
						</cs_xform>
						<color_palette>5</color_palette>
						<ncolors>9</ncolors>
						<outer_minmax_coloring>0</outer_minmax_coloring>
						<outer_min_color>16711680</outer_min_color>
						<outer_max_color>255</outer_max_color>
						<outer_colors_display>true</outer_colors_display>
						<logarithmic>false</logarithmic>
						<custom_params_maxs>
							<88A4B00C-3C32-4822-94C2-4682145D4F95>
								<value>102730.07982447979</value>
								<is_initialized>true</is_initialized>
								<is_global>true</is_global>
								<is_plot>false</is_plot>
							</88A4B00C-3C32-4822-94C2-4682145D4F95>
						</custom_params_maxs>
						<custom_params_mins>
							<88A4B00C-3C32-4822-94C2-4682145D4F95>
								<value>100842.39007741267</value>
								<is_initialized>true</is_initialized>
								<is_global>true</is_global>
								<is_plot>false</is_plot>
							</88A4B00C-3C32-4822-94C2-4682145D4F95>
						</custom_params_mins>
						<cs_name/>
						<display_plot_names>true</display_plot_names>
						<display_plot_minmaxes>false</display_plot_minmaxes>
						<display_title>false</display_title>
						<title/>
						<auto_scale_font>false</auto_scale_font>
						<use_default_font>true</use_default_font>
						<font>
							<name>Arial</name>
							<size>9</size>
							<color>0</color>
							<font_isbold>false</font_isbold>
							<font_isitalic>false</font_isitalic>
						</font>
						<bkgd_color>16777215</bkgd_color>
						<bkgd_transp>1</bkgd_transp>
						<x>488</x>
						<y>38</y>
						<width>20</width>
						<height>200</height>
						<auto_ticks>true</auto_ticks>
						<ticks_number>11</ticks_number>
						<vertical>3</vertical>
						<rot_text>false</rot_text>
						<is_user_pos>true</is_user_pos>
					</palette>
					<color_by_param>false</color_by_param>
					<color>0</color>
					<vectors_projected>true</vectors_projected>
					<arrow_size>0.02</arrow_size>
					<spacing>0.01</spacing>
					<minmax_arrowsize_ratio>0.001</minmax_arrowsize_ratio>
					<logarithmic_arrows>false</logarithmic_arrows>
					<vistype>0</vistype>
					<dynamic>
						<enabled>false</enabled>
						<width>6</width>
						<arrow_size>32</arrow_size>
						<spacing>8</spacing>
					</dynamic>
				</vectors>
				<essslic>
					<display>false</display>
					<build_palette>
						<uuid>c2eb71c5-9a66-48b8-b426-9878fd621a82</uuid>
						<parameter>
							<uuid>8A88FD9A-C36E-4151-864A-F5BC1C916074</uuid>
							<name/>
							<unit>0</unit>
							<formula/>
							<formula2/>
							<formula3/>
							<locality>0</locality>
						</parameter>
						<param_min>
							<value>0</value>
							<is_initialized>false</is_initialized>
							<is_global>true</is_global>
							<is_plot>false</is_plot>
						</param_min>
						<param_max>
							<value>0</value>
							<is_initialized>false</is_initialized>
							<is_global>true</is_global>
							<is_plot>false</is_plot>
						</param_max>
						<cs_uuid/>
						<cs_xform>
							<item>1</item>
							<item>0</item>
							<item>0</item>
							<item>0</item>
							<item>1</item>
							<item>0</item>
							<item>0</item>
							<item>0</item>
							<item>1</item>
							<item>0</item>
							<item>0</item>
							<item>0</item>
							<item>1</item>
							<item>0</item>
							<item>0</item>
							<item>0</item>
						</cs_xform>
						<color_palette>5</color_palette>
						<ncolors>10</ncolors>
						<outer_minmax_coloring>0</outer_minmax_coloring>
						<outer_min_color>16711680</outer_min_color>
						<outer_max_color>255</outer_max_color>
						<outer_colors_display>false</outer_colors_display>
						<logarithmic>false</logarithmic>
						<custom_params_maxs/>
						<custom_params_mins/>
						<cs_name/>
						<display_plot_names>true</display_plot_names>
						<display_plot_minmaxes>false</display_plot_minmaxes>
						<display_title>false</display_title>
						<title/>
						<auto_scale_font>false</auto_scale_font>
						<use_default_font>true</use_default_font>
						<font>
							<name/>
							<size>9</size>
							<color>0</color>
							<font_isbold>false</font_isbold>
							<font_isitalic>false</font_isitalic>
						</font>
						<bkgd_color>16777215</bkgd_color>
						<bkgd_transp>1</bkgd_transp>
						<x>0</x>
						<y>0</y>
						<width>20</width>
						<height>200</height>
						<auto_ticks>true</auto_ticks>
						<ticks_number>11</ticks_number>
						<vertical>3</vertical>
						<rot_text>false</rot_text>
						<is_user_pos>false</is_user_pos>
					</build_palette>
					<palette>
						<uuid>8990731f-264f-49c2-a158-5e2da04f94f9</uuid>
						<parameter>
							<uuid>88A4B00C-3C32-4822-94C2-4682145D4F95</uuid>
							<name>Pressure</name>
							<unit>14</unit>
							<formula/>
							<formula2/>
							<formula3/>
							<locality>0</locality>
						</parameter>
						<param_min>
							<value>100842.39007741267</value>
							<is_initialized>true</is_initialized>
							<is_global>true</is_global>
							<is_plot>false</is_plot>
						</param_min>
						<param_max>
							<value>102730.07982447979</value>
							<is_initialized>true</is_initialized>
							<is_global>true</is_global>
							<is_plot>false</is_plot>
						</param_max>
						<cs_uuid/>
						<cs_xform>
							<item>1</item>
							<item>0</item>
							<item>0</item>
							<item>0</item>
							<item>1</item>
							<item>0</item>
							<item>0</item>
							<item>0</item>
							<item>1</item>
							<item>0</item>
							<item>0</item>
							<item>0</item>
							<item>1</item>
							<item>0</item>
							<item>0</item>
							<item>0</item>
						</cs_xform>
						<color_palette>5</color_palette>
						<ncolors>9</ncolors>
						<outer_minmax_coloring>0</outer_minmax_coloring>
						<outer_min_color>16711680</outer_min_color>
						<outer_max_color>255</outer_max_color>
						<outer_colors_display>true</outer_colors_display>
						<logarithmic>false</logarithmic>
						<custom_params_maxs>
							<88A4B00C-3C32-4822-94C2-4682145D4F95>
								<value>102730.07982447979</value>
								<is_initialized>true</is_initialized>
								<is_global>true</is_global>
								<is_plot>false</is_plot>
							</88A4B00C-3C32-4822-94C2-4682145D4F95>
						</custom_params_maxs>
						<custom_params_mins>
							<88A4B00C-3C32-4822-94C2-4682145D4F95>
								<value>100842.39007741267</value>
								<is_initialized>true</is_initialized>
								<is_global>true</is_global>
								<is_plot>false</is_plot>
							</88A4B00C-3C32-4822-94C2-4682145D4F95>
						</custom_params_mins>
						<cs_name/>
						<display_plot_names>true</display_plot_names>
						<display_plot_minmaxes>false</display_plot_minmaxes>
						<display_title>false</display_title>
						<title/>
						<auto_scale_font>false</auto_scale_font>
						<use_default_font>true</use_default_font>
						<font>
							<name>Arial</name>
							<size>9</size>
							<color>0</color>
							<font_isbold>false</font_isbold>
							<font_isitalic>false</font_isitalic>
						</font>
						<bkgd_color>16777215</bkgd_color>
						<bkgd_transp>1</bkgd_transp>
						<x>488</x>
						<y>38</y>
						<width>20</width>
						<height>200</height>
						<auto_ticks>true</auto_ticks>
						<ticks_number>11</ticks_number>
						<vertical>3</vertical>
						<rot_text>false</rot_text>
						<is_user_pos>true</is_user_pos>
					</palette>
					<color_by_param>false</color_by_param>
					<color>0</color>
					<vistype>0</vistype>
					<esss_vistype>0</esss_vistype>
					<esss_linespacing>12</esss_linespacing>
					<esss_linewidth>2</esss_linewidth>
					<lic_noisegrainsize>1</lic_noisegrainsize>
					<lic_noisedensity>0.5</lic_noisedensity>
					<lic_contrast>0.10000000000000001</lic_contrast>
					<lic_convsize>64</lic_convsize>
				</essslic>
				<mesh>
					<display>false</display>
					<color>0</color>
				</mesh>
				<background>
					<display>false</display>
					<color>16777215</color>
				</background>
				<outlines_display>true</outlines_display>
				<outlines_color>0</outlines_color>
				<DeformedShape>
					<uuid>f5dfb0fd-42f2-435a-8751-032899014203</uuid>
					<creation_date>1756236503</creation_date>
					<enabled>false</enabled>
					<auto_scale>true</auto_scale>
					<scale/>
					<mode>-1</mode>
				</DeformedShape>
				<medias>
					<item>1</item>
				</medias>
				<mesh_type>0</mesh_type>
				<MeshTypePriority>0</MeshTypePriority>
				<use_offset>false</use_offset>
				<MediaPriority>1</MediaPriority>
			</data>
		</item>
	</features>
	<template_id>81bb07f2-edc5-4151-b7b4-b781cd50f430</template_id>
</feature>
