<?xml version="1.0" encoding="utf-8"?>
<feature>
	<version>1</version>
	<uuid>9c6a9f83-2879-4296-a1df-8802065ae76a</uuid>
	<name>Mesh 1</name>
	<type>12</type>
	<res_file_key>f752f969-8543-49ff-a2cc-6d932e75e4ec</res_file_key>
	<cs_name/>
	<cs_uuid/>
	<x_form>
		<global>true</global>
		<origin>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</origin>
		<translate>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
		</translate>
	</x_form>
	<display_bl>false</display_bl>
	<interpolate>true</interpolate>
	<use_cad_geom>false</use_cad_geom>
	<moving_reference>true</moving_reference>
	<moving_display>true</moving_display>
	<full_task>false</full_task>
	<use_in_BRP>false</use_in_BRP>
	<transparency>0</transparency>
	<box>
		<item>nan</item>
		<item>nan</item>
		<item>nan</item>
		<item>nan</item>
		<item>nan</item>
		<item>nan</item>
	</box>
	<crop_region_anchors>
		<item>false</item>
		<item>false</item>
		<item>false</item>
		<item>false</item>
		<item>false</item>
		<item>false</item>
	</crop_region_anchors>
	<section_plane/>
	<use_all_faces>false</use_all_faces>
	<geom_ref>
		<item>
			<uuid>0892d366-71fc-4dc2-8d30-b7926484fb09</uuid>
			<name>Face&lt;1&gt;@zphr-aerod-5.1 cm Fin Can-v2_1&lt;1&gt;</name>
			<type>5</type>
			<id1>0</id1>
			<id2>0</id2>
			<update_stamp>0</update_stamp>
			<group>0</group>
			<geom_stamp_uuid>84c30ed2-3ea7-486a-a249-c94490be07c6</geom_stamp_uuid>
			<origin>
				<item>0.69199959471957406</item>
				<item>0.21764726210023522</item>
				<item>5.858048920948332</item>
			</origin>
			<normal>
				<item>-0.24264109091169866</item>
				<item>0.95450887333072465</item>
				<item>0.17331506493692747</item>
			</normal>
			<vector>
				<item>0.58123819371909613</item>
				<item>0</item>
				<item>0.81373347120673523</item>
			</vector>
			<pos>0</pos>
			<flip>1</flip>
			<min>-7.84225304143839</min>
			<max>9.7821242873018299</max>
			<curve_data>
				<start>0</start>
				<end>0</end>
				<length>0</length>
				<data/>
			</curve_data>
			<path>
				<path_elems/>
			</path>
		</item>
	</geom_ref>
	<section_def_mode>0</section_def_mode>
	<xyz_plane>0</xyz_plane>
	<points>
		<item>500</item>
		<item>500</item>
		<item>400</item>
		<item>400</item>
	</points>
	<camera>
		<origin>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</origin>
		<up>
			<item>0</item>
			<item>1</item>
			<item>0</item>
		</up>
		<direction>
			<item>0</item>
			<item>0</item>
			<item>-1</item>
		</direction>
		<scale>1</scale>
	</camera>
	<display>0</display>
	<cut_with_section>false</cut_with_section>
	<section_medias>
		<item>1</item>
	</section_medias>
	<mesh_type>0</mesh_type>
	<surface_media>1</surface_media>
	<MeshTypePriority>0</MeshTypePriority>
	<MediaPriority>1</MediaPriority>
	<contours>
		<display>true</display>
		<palette>
			<uuid>02d3efd2-5a0c-4fae-a49b-27e6bcbe46d5</uuid>
			<parameter>
				<uuid>46096123-A86C-43c8-B809-DB1C7CB2E6AA</uuid>
				<name/>
				<unit>0</unit>
				<formula/>
				<formula2/>
				<formula3/>
				<locality>0</locality>
			</parameter>
			<param_min>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_min>
			<param_max>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_max>
			<cs_uuid/>
			<cs_xform>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</cs_xform>
			<color_palette>5</color_palette>
			<ncolors>10</ncolors>
			<outer_minmax_coloring>0</outer_minmax_coloring>
			<outer_min_color>16711680</outer_min_color>
			<outer_max_color>255</outer_max_color>
			<outer_colors_display>false</outer_colors_display>
			<logarithmic>false</logarithmic>
			<custom_params_maxs/>
			<custom_params_mins/>
			<cs_name/>
			<display_plot_names>true</display_plot_names>
			<display_plot_minmaxes>false</display_plot_minmaxes>
			<display_title>false</display_title>
			<title/>
			<auto_scale_font>false</auto_scale_font>
			<use_default_font>true</use_default_font>
			<font>
				<name/>
				<size>9</size>
				<color>0</color>
				<font_isbold>false</font_isbold>
				<font_isitalic>false</font_isitalic>
			</font>
			<bkgd_color>16777215</bkgd_color>
			<bkgd_transp>1</bkgd_transp>
			<x>0</x>
			<y>0</y>
			<width>20</width>
			<height>200</height>
			<auto_ticks>true</auto_ticks>
			<ticks_number>11</ticks_number>
			<vertical>3</vertical>
			<rot_text>false</rot_text>
			<is_user_pos>false</is_user_pos>
		</palette>
		<color_by_param>true</color_by_param>
		<color>0</color>
	</contours>
	<mesh>
		<display>true</display>
		<color>0</color>
	</mesh>
	<cell_mode>0</cell_mode>
	<color>62207</color>
	<aspect>10</aspect>
	<percentage>0.20000000000000001</percentage>
	<channels>
		<palette>
			<uuid>fb6ddcea-394d-4128-acc4-e0ab5fdb8c73</uuid>
			<parameter>
				<uuid>FFB784BF-E692-40E4-AF7C-D8CE07F6C372</uuid>
				<name/>
				<unit>0</unit>
				<formula/>
				<formula2/>
				<formula3/>
				<locality>0</locality>
			</parameter>
			<param_min>
				<value>1.222551548996172e-05</value>
				<is_initialized>true</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_min>
			<param_max>
				<value>1.6085306241704802</value>
				<is_initialized>true</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_max>
			<cs_uuid/>
			<cs_xform>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</cs_xform>
			<color_palette>5</color_palette>
			<ncolors>9</ncolors>
			<outer_minmax_coloring>2</outer_minmax_coloring>
			<outer_min_color>16711680</outer_min_color>
			<outer_max_color>255</outer_max_color>
			<outer_colors_display>false</outer_colors_display>
			<logarithmic>false</logarithmic>
			<custom_params_maxs>
				<FFB784BF-E692-40E4-AF7C-D8CE07F6C372>
					<value>1.6085306241704802</value>
					<is_initialized>true</is_initialized>
					<is_global>true</is_global>
					<is_plot>false</is_plot>
				</FFB784BF-E692-40E4-AF7C-D8CE07F6C372>
			</custom_params_maxs>
			<custom_params_mins>
				<FFB784BF-E692-40E4-AF7C-D8CE07F6C372>
					<value>1.222551548996172e-05</value>
					<is_initialized>true</is_initialized>
					<is_global>true</is_global>
					<is_plot>false</is_plot>
				</FFB784BF-E692-40E4-AF7C-D8CE07F6C372>
			</custom_params_mins>
			<cs_name/>
			<display_plot_names>true</display_plot_names>
			<display_plot_minmaxes>false</display_plot_minmaxes>
			<display_title>false</display_title>
			<title/>
			<auto_scale_font>false</auto_scale_font>
			<use_default_font>true</use_default_font>
			<font>
				<name/>
				<size>9</size>
				<color>0</color>
				<font_isbold>false</font_isbold>
				<font_isitalic>false</font_isitalic>
			</font>
			<bkgd_color>16777215</bkgd_color>
			<bkgd_transp>1</bkgd_transp>
			<x>0</x>
			<y>0</y>
			<width>20</width>
			<height>200</height>
			<auto_ticks>true</auto_ticks>
			<ticks_number>11</ticks_number>
			<vertical>3</vertical>
			<rot_text>false</rot_text>
			<is_user_pos>false</is_user_pos>
		</palette>
		<mesh>true</mesh>
		<color>0</color>
		<interpolate>true</interpolate>
	</channels>
</feature>
